name: Android Module CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  unit-tests:
    name: Run Unit Tests & Coverage
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Set up JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    # 3. Cache Gradle dependencies
    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper/
        key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: gradle-

    # 4. Build module and run Unit Tests
    - name: Build & Run Unit Tests
      run: ./gradlew :<module-name>:cleanTest :<module-name>:testDebugUnitTest

    # 5. Generate test coverage (optional, requires JaCoCo plugin)
    - name: Generate Coverage Report
      run: ./gradlew :<module-name>:jacocoTestReport

    # 6. Upload coverage as artifact
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: <module-name>/build/reports/jacoco/jacocoTestReport/html
