name: Android Module CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  unit-tests:
    name: Run Unit Tests & Coverage
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Set up JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    # 3. Cache Gradle dependencies
    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper/
        key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: gradle-

    # 4. Build module and run Unit Tests
    - name: Build & Run Unit Tests
      run: ./gradlew :forceupdatekit:cleanTest :forceupdatekit:testDebugUnitTest

    # 5. Generate test coverage (optional, requires JaCoCo plugin)
    - name: Generate Coverage Report
      run: ./gradlew :forceupdatekit:jacocoTestReport

    # 6. Upload coverage as artifact
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: forceupdatekit/build/reports/jacoco/jacocoTestReport/html
