name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      # ۱. Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # ۲. Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # ۳. Cache Gradle
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      # ۴. Run Gradle tests and build
      - name: Run tests
        run: ./gradlew clean testDebugUnitTest --stacktrace

      # ۵. Generate JaCoCo coverage report
      - name: Generate JaCoCo report
        run: ./gradlew jacocoTestReport
